### ISSUE TITLE
Portfolio application deployed

### ISSUE THREAD

**Issue by FevenSeyfu** [FevenSeyfu/portfolio-v1#10]
My Project is  deployed on GitHub Pages and can be accessed through this link https://fevenseyfu.github.io/portfolio-v1/

**Comment by TadesseDev** [comment]
### Hi @FevenSeyfu 

### I'm Tadesse Alemayehu your reviewer for this milestone.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![gabriel_Igla](https://user-images.githubusercontent.com/69077061/208483190-80442224-73eb-4d21-9ef7-44c94484c9e1.gif)


## Highlights
- Good job adding the link to the live README file. ✌️
## Optional suggestions
- 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by FevenSeyfu** [comment]
Thank you!
